import { Inter } from "next/font/google";
import UseAuth from "@/context/useAuth";
import "./globals.css";
import Loading from "./loading";
import Navbar from "@/components/Navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Travel Rate Scraping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <UseAuth>{children ? children : <Loading />}</UseAuth>
      </body>
    </html>
  );
}
